### ISSUE TITLE
"VueJS not detected" on production server

### ISSUE THREAD

**Issue by keamarg** [susanBuck/e28-spring21#27] opened 2021-04-12 08:16 UTC
**Environment**
Production server

**What operating system are you using?**
MacOS Big Sur 11.2.3

**Describe the problem**
Vue devtools are not working on my production server when using build versions. I get the message "VueJS not detected" (it works fine for the previous non-build versions we used). I have a feeling I may have forgotten something you already covered in the videos, so if that's the case I am sorry. 

**Steps taken**
I tried uninstalling and reinstalling the VueJS extension and toggling the "Allow access to file URLs" to on.

**Additional context**
The reason I wanted to access the devtools on production is that I wanted to troubleshoot this error I keep getting ONLY on the production server:

"Cannot read property 'includes' of null; related to this piece of code

```
  computed: {
    featuredProducts() {
      return this.products.filter((product) => {
        return product.categories.includes(this.category);
      }, this.category);
    },
  },
```
I know you went through the issue of the data not being ready on access, but as far as I remember it should be OK when using a computed property (or maybe I should create it on the mounted hook instead).

**Comment by susanBuck** [comment] 2021-04-12 15:23
Hi @keamarg -

That's by design.

Ref: https://github.com/vuejs/vue-devtools#important-usage-notes

> _If the page uses a production/minified build of Vue.js, devtools inspection is disabled by default so the Vue pane won't show up._

Can you tell me what page I can visit to recreate the error you're describing?

The fact that it works locally but not on production makes me think the error is possibly related to accessing your API since that's the main thing that differs between the two environments.

**Comment by keamarg** [comment] 2021-04-12 15:30
Hi Susan

> That's by design.

I thought that might be the case.

Here is the link to the production server:
[ZipFoods](http://e28zipfoods.hesdev.com/
)

Br,

Martin

**Comment by susanBuck** [comment] 2021-04-12 15:49
I'm getting varied results when I test the site.

Sometimes it loads fine, including products from the API. 

Other times it produces a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error:

![image](https://user-images.githubusercontent.com/237711/114422842-a0299480-9b84-11eb-8835-470a6ce76a0a.png)

Other times it won't load at all w/ a 404 error:

![image](https://user-images.githubusercontent.com/237711/114422959-b9324580-9b84-11eb-9649-dd48b0296340.png)

I did a [DNS lookup on your domain](https://mxtoolbox.com/SuperTool.aspx?action=a%3ae28zipfoods.hesdev.com&run=toolpage) and see you have two A records:

![image](https://user-images.githubusercontent.com/237711/114423140-e3840300-9b84-11eb-9c39-1ef673bb4848.png)

I believe this might be the source of the problems - I suspect sometimes it's resolving to one IP address and it works okay, other times it resolves to the other and fails.

Can you check on your DNS settings and remove the extra A record, leaving just the one that is pointing to your DigitalOcean server (164.90.130.30) ?

**Comment by keamarg** [comment] 2021-04-12 18:24
I have had some weird problems with Chrome often giving 404's on load, probably related to that as well...

I just checked both Digital Ocean and Namecheap dashboard, and as far as I can tell, there is only one A record, but I am a bit out of my territory tbh, maybe I am looking in the wrong place?

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/75420074/114442166-8ca21c00-9bcc-11eb-8cf3-435f59623a0e.png">

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/75420074/114442256-a9d6ea80-9bcc-11eb-96b0-4bdc9c7252d1.png">

I wonder if it is connected to this issue here [link](https://serverfault.com/questions/803805/why-does-my-domain-have-a-records-for-two-ip-addresses-when-i-only-have-one-ser)

**Comment by susanBuck** [comment] 2021-04-12 18:49
Try getting rid of the last record, _URL Redirect Record_. 

It's the only difference I see between your settings and my example settings:

![image](https://user-images.githubusercontent.com/237711/114445469-1dadce80-9b9e-11eb-91e9-330f8d96d3a1.png)

**Comment by keamarg** [comment] 2021-04-12 20:04
That seemed to do the trick for the [double A record!](https://mxtoolbox.com/SuperTool.aspx?action=a%3ae28zipfoods.hesdev.com&run=toolpage
)
Still getting the "Cannot read property 'includes' of null" error though...

**Comment by susanBuck** [comment] 2021-04-12 20:12
Excellent! That'll make it easier to debug since it's now consistently loading. : ) Looking at the "includes of null" error now. Will report back shortly with what I find.

**Comment by susanBuck** [comment] 2021-04-12 20:43
Looking closer at this, this comes down to **an issue created by "new products" that are added without categories.** 

It's related to an issue described in Week 10's assignment practice:
![image](https://user-images.githubusercontent.com/237711/114458638-70db4d80-9bad-11eb-8fc6-1d84447d2c47.png)

Right now if we look at your production data/api at http://e28api.hesdev.com/product we can see the last two "new products" have a categories value of null: 
![image](https://user-images.githubusercontent.com/237711/114458748-99fbde00-9bad-11eb-9b04-4e48372db06b.png)

In the code, the featured products does iterating through the products and expects a value for _categories_ When it's not there, it causes the error you're seeing.

If you're not seeing the same error locally, I suspect it's because you haven't added a product locally, or have recently rebuilt the API fresh. In either case, you wouldn't have any products without categories, and thus you wouldn't see any errors.

So, going back to the assignment/practice prompt - how could we fix this?

There's a couple ways I can think of: 
1. Make it so the code does not break if no categories are available 
2. Make it so that categories can be included as part of the new product data

**Comment by keamarg** [comment] 2021-04-12 21:22
Ahh, that makes perfect sense! I fixed the issue already, so I will probably just need to rebuild the online version of the API. It is getting late here now, so I will look into it tomorrow.

Thanks a lot for helping out with both issues!

**Comment by keamarg** [comment] 2021-04-12 21:25
Fix was so simple I could do it from my phone. All good now:-)

Thanks again.

**Comment by susanBuck** [comment] 2021-04-13 04:15
Glad it's sorted out! : )

**Closed by susanBuck** 2021-04-13 04:15 UTC
